### ISSUE TITLE
Only up to 40% of entries are loaded from db snapshot

### ISSUE THREAD

**Issue by EmiM** [orbitdb/orbitdb#900] opened 2021-07-29 14:46 UTC
Hello, 
I have a question regarding snapshots. I’m seeing that loading a snapshot containing 1000 entries results in only 10-40% of entries being loaded, with the rest failing in timeouts.

I performed a test with saving snapshot on one running node and retrieving it and loading on another node.
This is the setup:
* Node1 has a db with 1000 entries (log of strings), it saves a snapshot. I ensure that node1 is always running.
* I manually copy snapshot data that is saved to ipfs (cid, snapshotPath, queuePath and unfinished queue) and paste to code handling node2.
* Node2 always starts with empty db. We want to test if loading snapshot would make initial sync faster.
* Node2 connects to node1, loads the snapshot (retrieved from ipfs). Retrieved data is intact and matches the one saved on node1.

The fetching part is confusing to me. Orbitdb always manages to load from 10% up to 40% of entries from the provided snapshot. The rest throws timeout:
`Warning: Couldn't fetch entry '<entryhash>', request timed out (1000ms)`

Also, it takes quite a lot of time. The last time loading data from snapshot I attached took 108218.136ms.

Why so many entries fail to load from the snapshot? Is it desired behavior? Did I miss some extra configuration/setup?

Btw. the released orbit-db version stops after loading snapshot (I don't see any replication of the missing entries) however the main branch (with newest orbit-db-store which is not in current package.json yet) fixes it.

**Comment by EmiM** [comment] 2021-07-29 14:55
Forgot to attach a file with snapshot data. Here it is: 
[loadedSnapshotData.log](https://github.com/orbitdb/orbit-db/files/6901441/loadedSnapshotData.log)

**Comment by aphelionz** [comment] 2021-07-29 21:44
@EmiM is it possible for you to contrive some example that I can reproduce?

**Comment by holmesworcester** [comment] 2021-07-29 21:52
@EmiM aphelionz would like to look into this but it would be helpful to have something that he can run himself and observe the failure. 

ideally we'd provide him with a failing test in `orbitdb/orbit-db` or `orbitdb/orbit-db-store`

if that's complicated for some reason, or if the bug doesn't appear there, can you create a repo for him that has the failing import, so that he can run and observe the failure?

**Comment by EmiM** [comment] 2021-07-29 23:14
Sure, I'll try to prepare something testable.
Btw. it's probably obvious for you but I measured that the most time-consuming part of fetching an entry is `ipfs.dag.get` in `readCbor` (orbit-db-io).
E.g `zdpuApZPbc3yNTMokjoW39FgHWyr5ERpWymyT15ErYjngeLWP readCbor time: 1413 ms` (with default timeout of 1s)

**Comment by aphelionz** [comment] 2021-07-29 23:24
Yeesh, one second just to read a dag node from IPFS :sweat:

**Comment by holmesworcester** [comment] 2021-07-30 12:40
So should the timeout be set higher?

**Comment by holmesworcester** [comment] 2021-07-30 12:41
Also, is this something we should create a js-ipfs issue for?

They've been very helpful and responsive so far.

**Comment by aphelionz** [comment] 2021-07-30 13:12
Setting the timeout higher will mitigate the issue but it's still curious to see it take such a long time in a local dev environment

**Comment by holmesworcester** [comment] 2021-07-30 16:09
@EmiM these are still getting loaded over Tor, correct? 

If that were the case, it's local but the requests are going out across the real Internet, and will be higher latency than normal.

**Comment by EmiM** [comment] 2021-07-30 16:38
Yes, that's right, we connect over tor so even local dev is not local 😅 
Of course we can increase the timeout but then loading entries from snapshot will take even longer (afaik).

**Comment by holmesworcester** [comment] 2021-07-30 17:11
Is this slowness in ipfs or orbitdb? if ipfs, should we create an issue?

**Comment by aphelionz** [comment] 2021-07-30 17:47
Hmm, could it simply be tor routing?

**Comment by holmesworcester** [comment] 2021-07-30 18:34
But 60% of requests shouldn’t fail, especially when we have persistent connections to peers. 

I mean, maybe it would be slower, but why would it fail completely?

**Comment by aphelionz** [comment] 2021-07-30 18:35
They would timeout after 1s which would cause the failure. Don't get me wrong - I think we should _definitely_ speed up replication even more but I would like to rule out as many factors as possible also

**Comment by holmesworcester** [comment] 2021-07-30 18:50
first, let’s increase the timeout 10x and see if importing a snapshot is faster than normal replication.

second, let’s see if tor is really the issue by setting up a test of snapshot import using nodes connected without tor, to confirm that tor is the issue. 

after that, these would be my questions:

1. is there some way to be in possession of a file that contains the data for all entries, and to import this file? (for example, you could do this by swapping in the full db file for whatever file the user already has).  

2. is there some way to be in a possession of a file that contains the data for some but not all entries, and import this in a way that merges it with whatever other entries the importing node already knows about? (you could not just swap in the new file in this case)

2. is there some way for a new peer to fetch *all* entries at close to the limit of another peer’s upstream bandwidth, and then import it?   

3. is there some way for a new peer to fetch all entries at close to the limit of all connected peers’ upstream bandwidth, and then import it? (downloading from a swarm?)

4. is there a way for a new peer to fetch all entries and parse/import them at close to the limit of all connected peers’ upstream bandwidth? 

5. is there a way for an existing peer to fetch and parse all entries they don’t already have from all connected peers at close to the limit of those peers’ upstream bandwidth?

Like, if Tor is slow that’s just fine. But Tor isn’t *that* slow, and the protocol should let us get close to the upstream bandwidth limits of peers (or the downstream limit of the peer that’s fetching). It seems like we’re really far from that now. Or are we?

**Comment by holmesworcester** [comment] 2021-08-02 16:22
We discussed this and decided that this timeout should never happen at all, Tor or not, because the data is present in the snapshot so a network request shouldn't even be necessary.

We could potentially update the name of the ticket to "Loading snapshot fails due to timeouts on unnecessary calls to network" or something for clarity, but the goal here is to fix importing of snapshots so that it happens fast and consistently regardless of the network.

**Comment by EmiM** [comment] 2021-08-11 13:05
@aphelionz Sorry for such a long wait. I made a separate branch on https://github.com/ZbayApp/waggle: `test/ipfs-initial-sync`, test and readme are in `src/nodeTest/README.md`.

If you have any questions feel free to ask. We can also talk through discord or something like this if you want, it would be faster than doing it via github issue.

**Comment by EmiM** [comment] 2021-08-20 13:30
FYI, tests are now in waggle's master branch in `src/nodeTest`. The most interesting for you @aphelionz (in tthe context of this issue) would be snapshotTestTor.ts (throwing timeouts) and snapshotTest.ts (for comparison).

**Comment by haydenyoung** [comment] 2023-11-06 16:48
Please test with latest OrbitDB. Closing for now.

**Closed by haydenyoung** 2023-11-06 16:48 UTC
Labels: bug, Difficulty: Medium
