### ISSUE TITLE
OrbitDB can't be opened - AggregateError: All promises were rejected 

### ISSUE THREAD

**Issue by silkroadnomad** [orbitdb/orbitdb#1173] opened 2024-03-25 06:37 UTC
From time to time in my Chrome browser (and also in an Opera instance) after deleting a record from a document type db, records of the db can't be read anymore. Reloading the browser doesn't help, no records can't be read at all.

An excecption is thrown, after db.all()
"AggregateError: All promises were rejected "

@orbitdb/core 2.1.0
helia 4.1.0

Current Workaround:

1. drop db when no peers are connected
2. reload browser, so browser reconnects to other peers
3. other browser peers with same db are replicating back (restore) - but broken record seems to be still in db

**Comment by haydenyoung** [comment] 2024-03-25 18:17
At a glance, the aggregate error would suggest an issue from reading records from the underlying IPFS blockstore. My hunch is that, for whatever reason, the in-memory blockstore is being unloaded and reloaded resulting in the inability for OrbitDB to read the blocks. Deleting a record may trigger a re-read of the blocks (perhaps for re-indexing).

Can I replicate the issue from deContact? If not, I'll hopefully have some time to try and set up a test to isolate the problem.

**Comment by silkroadnomad** [comment] 2024-03-26 07:42
I'll try to give you some more info on how to reproduce it. For now I got a better error message:

exception while opening (reading) dbMyAddressBook AggregateError: All promises were rejected

promise) Error: Database is not open
    at BrowserLevel.iterator (2.Dj7UZdDY.js:201:45244)
    at Object.iterator (2.Dj7UZdDY.js:201:56728)
    at iterator.next (<anonymous>)
    at Object.iterator (2.Dj7UZdDY.js:201:2863)
    at async l (2.Dj7UZdDY.js:199:26301)
    at async Object.c [as all] (2.Dj7UZdDY.js:199:26375)
    at async T (2.Dj7UZdDY.js:199:28154)
    at async Object.Z [as iterator] (2.Dj7UZdDY.js:201:1565)
    at async q (2.Dj7UZdDY.js:201:59667)
    at async Object.all (2.Dj7UZdDY.js:20

**Comment by silkroadnomad** [comment] 2024-03-26 09:24
I can't reproduce it anymore. But I guess it is hiding somewhere around the corner. But until then I'll close the issue to reduce the whole noise it makes. ;)

**Comment by silkroadnomad** [comment] 2024-03-26 10:44
Just made another test with two Brave browsers (one Mac - one Linux) with a collegue and could reproduce the problem one more time following scenario:

1) I added a record on my Brave (fresh identity with fresh and clean db)
2) Collegue added a record (fresh identity with fresh and clean db)
3) College replicated my db and wrote a record into my db
4) I replicated his db and wrote a record into his db
5) Replications ok - I deleted his record in my db -> db crash

I will try now to reproduce this with another person!

**Comment by silkroadnomad** [comment] 2024-03-26 12:45
Another Test with two DuckDuckGo Browser (Safari Clone) which are distant to each other immediatly resulted in a corrupted db when the remote party deleted an entry of my db.

**Comment by haydenyoung** [comment] 2024-04-16 21:14
After testing with both @silkroadnomad and the libp2p devs, we are thinking the problem is related to the stream returned by libp2p.dial() prematurely breaking. According to the libp2p devs, the a connection should be re-established but this does not seem to be the case. The workaround suggestion is to provide some kind of keep-alive to ensure two peers are reconnected if the connection prematurely ends.

**Comment by Keref** [comment] 2024-06-17 08:49
I have the issue with an app where clients can write an entry for themselves in a public DB. If the DB doesnt sync well it can reach this state, without any record delete.
I'm not sure how it works behind the hood but what I see is that the last DB write isnt propagated, but on restarting the process the client will query my persistent bootstrap server who will try to find a non existent CID and crash.

After that I have to remove the DB state or opening the DB will always crash looking for a non existing CID.
It looks like the DB gets corrupted if some data chunk is missing, it happens regularly as I'm in dev and reload client apps often (nextjs reloads)

On my node process:
```      [errors]: [
        Error: fetching raw block for CID bafyreieb7qahxwpzcu6hj7424yapfsqd57mbtsmbhy5kyk2nkjz453n3au from gateway https://trustless-gateway.link/ was aborted
```

**Comment by haydenyoung** [comment] 2024-06-17 09:13
> I have the issue with an app where clients can write an entry for themselves in a public DB. If the DB doesnt sync well it can reach this state, without any record delete. I'm not sure how it works behind the hood but what I see is that the last DB write isnt propagated, but on restarting the process the client will query my persistent bootstrap server who will try to find a non existent CID and crash.
> 
> After that I have to remove the DB state or opening the DB will always crash looking for a non existing CID. It looks like the DB gets corrupted if some data chunk is missing, it happens regularly as I'm in dev and reload client apps often (nextjs reloads)
> 
> On my node process:
> 
> ```
>         Error: fetching raw block for CID bafyreieb7qahxwpzcu6hj7424yapfsqd57mbtsmbhy5kyk2nkjz453n3au from gateway https://trustless-gateway.link/ was aborted
> ```
> 
> Have you found any way to avoid this error? Hopefully I'm doing smth wrong, bc if the DB can get corrupted and cant be used anymore it is quite a critical issue.

Are you using a persistent blockstore with IPFS? It sounds like restarting the OrbitDB service clears any blocks in the blockstore which would result in a failed fetch of the block.

See https://github.com/orbitdb/orbitdb/blob/main/docs/GETTING_STARTED.md#block-storage for configuring a persistent blockstore.

If the problem persists, are you able to provide some kind of basic script to replicate the problem?

**Comment by GreenCodeLine** [comment] 2024-07-21 13:49
I have same error "createDBAggregateError: All promises were rejected".
When i open db with any address in my chrome.

**Comment by haydenyoung** [comment] 2024-07-21 21:36
> I have same error "createDBAggregateError: All promises were rejected". When i open db with any address in my chrome.

This usually means the db address you are trying to replicate cannot be reached.

Could you please provide more information as to how you are connecting your peer to other peers (libp2p configuration, helia configuration, etc)?

**Comment by haydenyoung** [comment] 2024-08-23 21:05
No further information has been provided so closing. Please feel free to re-open if more information about the problem is available.

**Closed by haydenyoung** 2024-08-23 21:05 UTC
Labels: bug, In Progress
