### ISSUE TITLE
Issue with `orbitdb demo`

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbitdb#619] opened 2019-05-03 17:36 UTC
I tried running `orbitdb demo`, and got this error:

```sh
 orbitdb demo Richard
                 _     _ _         _ _
                | |   (_) |       | | |
       ___  _ __| |__  _| |_    __| | |__
      / _ \| '__| '_ \| | __|  / _` | '_ \
     | (_) | |  | |_) | | |_  | (_| | |_) |
      \___/|_|  |_.__/|_|\__|  \__,_|_.__/

             Peer-to-Peer Database
       https://github.com/orbitdb/orbit-db

> node "orbitdb" create /orbitdb/demo docstore
/orbitdb/zdpuApr9BZKRmFnoLQtJGWGh7NTEjVGe6ZfP4ZDWzxqzUhyKi/orbitdb/demo

> node "orbitdb" put /orbitdb/zdpuApr9BZKRmFnoLQtJGWGh7NTEjVGe6ZfP4ZDWzxqzUhyKi/orbitdb/demo "{\"_id\":1,\"name\":\"Richard\"}" --indexBy name
Error: Cannot read property 'sign' of undefined
/Users/richard/.nvm/versions/node/v10.15.3/lib/node_modules/orbit-db-cli/node_modules/yargs/yargs.js:1101
      else throw err
           ^

Error: Command failed: node "/Users/richard/.nvm/versions/node/v10.15.3/lib/node_modules/orbit-db-cli/src/bin" put /orbitdb/zdpuApr9BZKRmFnoLQtJGWGh7NTEjVGe6ZfP4ZDWzxqzUhyKi/orbitdb/demo "{\"_id\":1,\"name\":\"Richard\"}" --indexBy name
Error: Cannot read property 'sign' of undefined

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at CLI (/Users/richard/.nvm/versions/node/v10.15.3/lib/node_modules/orbit-db-cli/src/cli.js:6:10)
    at Object.exports.handler (/Users/richard/.nvm/versions/node/v10.15.3/lib/node_modules/orbit-db-cli/src/commands/demo.js:40:19)
    at Object.runCommand (/Users/richard/.nvm/versions/node/v10.15.3/lib/node_modules/orbit-db-cli/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/richard/.nvm/versions/node/v10.15.3/lib/node_modules/orbit-db-cli/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/Users/richard/.nvm/versions/node/v10.15.3/lib/node_modules/orbit-db-cli/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/richard/.nvm/versions/node/v10.15.3/lib/node_modules/orbit-db-cli/src/bin.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
```

Any ideas?

**Comment by haydenyoung** [comment] 2019-05-05 13:28
The problem appears to be with the ipfs-log dependency version. The official node package is referencing "next" and using the latest repo code references 4.1.0. However, I think the version is up to 4.3.0?

**Comment by haydenyoung** [comment] 2019-05-05 14:31
an incompatible method call to IPFS Log append seems to be the problem and results in the log entry trying to use the keystore instead of the identity object to sign the log entry.

**Comment by haydenyoung** [comment] 2019-05-05 15:27
Sorry my mistake. The problem is with instantiation of OrbitDB. create-database.js and open-database.js should be using OrbitDB.createInstance()?

**Comment by aphelionz** [comment] 2019-05-05 18:00
From 0.20.0 on the OrbitDB object should be created with `OrbitDB.createInstance` yes

**Comment by haydenyoung** [comment] 2019-05-06 14:41
> From 0.20.0 on the OrbitDB object should be created with `OrbitDB.createInstance` yes

I have managed to get it working by implementing createInstance but I also had to change some of the dependency versions to fix a couple of other issues. I can submit a pull request of my changes but they may require further review.

**Comment by aphelionz** [comment] 2019-05-06 14:46
@haydenyoung Thank you! Please make the PR. If nothing else it will be helpful for analysis + discussion

**Comment by haydenyoung** [comment] 2019-05-06 15:24
@aphelionz Done. https://github.com/orbitdb/orbit-db-cli/pull/27.

**Comment by aphelionz** [comment] 2019-05-06 15:26
That's awesome @haydenyoung, thank you. On a related note, should we plan on starting to migrate the orbit-db-cli to use the HTTP api?

**Comment by haydenyoung** [comment] 2019-05-06 15:37
@aphelionz If that's the plan, then, yeah, for sure.

**Comment by haydenyoung** [comment] 2023-11-06 16:28
Closing. We need to overhaul demo with v1.

**Closed by haydenyoung** 2023-11-06 16:28 UTC
